name: Sync Git Folder

concurrency: prod_environment

on:
  push:
    branches:
      # Set your base branch name here
      [git-folder-cicd-example, main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Update git folder'
    # environment: Prod
    env:
      DATABRICKS_AUTH_TYPE: github-oidc

      
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo DATABRICKS_HOST=$(az keyvault secret show --name "databricks-workspace-url" --vault-name ${{ secrets.AZURE_KEY_VAULT_NAME }} --query "value") >> $GITHUB_ENV
            echo DATABRICKS_CLIENT_ID=$(az keyvault secret show --name "databricks-workspace-id" --vault-name ${{ secrets.AZURE_KEY_VAULT_NAME }} --query "value") >> $GITHUB_ENV

      
      - uses: databricks/setup-cli@main
      - name: Update git folder
        # Set your workspace path and branch name here
        run: databricks repos update /Shared/wellanalysisstream --branch main
